# Project config
---
  --main:
     --data_root: "/cvlabscratch/cvlab/home/engilber/dev/MARMOT/data" # "/Users/sarno/Documents/GitHub/Pomelo/data" #"/root/data"
     --code_root: "/cvlabscratch/cvlab/home/engilber/dev/MARMOT/code" # "/Users/sarno/Documents/GitHub/Pomelo/code" #"/root/code"
     --data: "/cvlabscratch/cvlab/home/engilber/dev/pomelo_test_data" #"/root/data" #

  --calibration:
   #   --focal_length: "507" # tag to be added to metadata
     --omni_tag: '360'     # tag to identify omnidirectional camera
     --opensfm_repo: "/source/OpenSfM/" #"/Users/grosche/Documents/GitHub/OpenSfM/"
  
  --annotation:
    --num_train_sample: "400"
    --val_seq_length: "100"

