# Project config
---
  --main:
     --data_root: "/cvlabscratch/cvlab/home/engilber/dev/MARMOT/data" # "/Users/sarno/Documents/GitHub/Pomelo/data" #"/root/data"
     --code_root: "/cvlabscratch/cvlab/home/engilber/dev/MARMOT/code" # "/Users/sarno/Documents/GitHub/Pomelo/code" #"/root/code"
     --data: "/cvlabscratch/cvlab/home/engilber/dev/pomelo_test_data" #"/root/data" #
     

  --calibration:
   #   --focal_length: "507" # tag to be added to metadata
     --omni_tag: '360'     # tag to identify omnidirectional camera
     --opensfm_repo: "/OpenSfM" #"/Users/grosche/Documents/GitHub/OpenSfM/"
     --omni_start: "1200"
     --omni_end: "2700"
     --omni_step: "30"
  
  --annotation:
    --num_train_sample: "400"
    --val_seq_length: "100"
    -val_seq_start: "0"

