# Project config
---
  --main:
     --data_root: "/root/data" # "/Users/sarno/Documents/GitHub/Pomelo/data" #"/root/data"
     --code_root: "/root/code" # "/Users/sarno/Documents/GitHub/Pomelo/code" #"/root/code"
     --data: "/root/data_source"

  --calibration:
   #   --focal_length: "507" # tag to be added to metadata
     --omni_tag: '360'     # tag to identify omnidirectional camera
     --opensfm_repo: "/OpenSfM"
  
  --annotation:
    --num_train_sample: "400"
    --val_seq_length: "100"

