---
  main:
  dataset:
    --metric_threshold : '5'
    --hm_size: 
      - "120"
      - "300"
    --hm_radius: '4'
    --crop_size:
      - "720"
      - "1080"
    --view_ids:
      - "0"
      - "1" 
      - "2"
  training:
    --detection_to_evaluate:
      - pred_0
      - framepred_0_v0
      - framepred_0_v1
      - framepred_0_v2
      
    --metric_to_print:
      - moda_pred_0
      - recall_pred_0
      - precision_pred_0
      - moda_framepred_0_v0
      - recall_framepred_0_v0
      - precision_framepred_0_v0
    --loss_to_print:
      - loss_pred
      - loss_framepred
    --image_pred:
    --aug_train:
    --views_based_aug_list:
      - "rcrop,0.5"
    --scene_based_aug_list:
      - "raff,0.5"

